const CONFIG = {
  DEFAULT_HEIGHT: screen.height,
  DEFAULT_WIDTH: screen.width,
  DEFAULT_GRAVITY: 200,
  CARD_WIDTH: 224,
  HAND_DEPTH: 3,
  HAND_ORBITAL: 1200,
  DRAWS_PER_ROUND: 4
}

export default CONFIG
